In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout, Activation, Input
from tensorflow.keras.regularizers import l2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [22]:
import numpy as np
import pandas as pd



np.random.seed(42)

n_samples = 500

area_m2 = np.random.randint(50, 251, n_samples)
bedrooms = np.random.randint(1, 6, n_samples)
bathrooms = np.random.randint(1, 4, n_samples)
age_years = np.random.randint(0, 31, n_samples)
distance_to_center_km = np.round(
    np.random.uniform(1, 20, n_samples), 1
)
floor = np.random.randint(1, 11, n_samples)


noise = np.random.normal(0, 30000, n_samples)

price = (
    50000
    + area_m2 * 3000
    + bedrooms * 25000
    + bathrooms * 15000
    - age_years * 2000
    - distance_to_center_km * 5000
    + floor * 3000
    + noise
)

price = np.maximum(price, 50000)

df = pd.DataFrame({
    "area_m2": area_m2,
    "bedrooms": bedrooms,
    "bathrooms": bathrooms,
    "age_years": age_years,
    "distance_to_center_km": distance_to_center_km,
    "floor": floor,
    "target": price.astype(int)
})

display(df.head())
print("Number of samples:", len(df))

,area_m2,bedrooms,bathrooms,age_years,distance_to_center_km,floor,target
0,152,1,1,17,1.6,7,514920
1,229,5,3,26,2.5,8,879481
2,142,5,1,9,8.5,3,546669
3,64,5,1,6,3.5,5,361730
4,156,3,1,16,11.8,1,504905

Number of samples: 500

In [23]:
FEATURES = [
    "area_m2",
    "bedrooms",
    "bathrooms",
    "age_years",
    "distance_to_center_km",
    "floor"
]

TARGET = "target"

In [24]:
X = df[FEATURES].values
y = df[TARGET].values

In [25]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42
)

In [26]:
y_scaler = StandardScaler()

y_train_scaled = y_scaler.fit_transform(
    y_train.reshape(-1, 1)
).ravel()

y_val_scaled = y_scaler.transform(
    y_val.reshape(-1, 1)
).ravel()

y_test_scaled = y_scaler.transform(
    y_test.reshape(-1, 1)
).ravel()

In [27]:
model = Sequential([

    Input(shape=(len(FEATURES),)),

    Dense(128, kernel_regularizer=l2(0.005)),
    BatchNormalization(),
    Activation("relu"),
    Dropout(0.3),

    Dense(64, kernel_regularizer=l2(0.005)),
    BatchNormalization(),
    Activation("relu"),
    Dropout(0.3),

    Dense(32, kernel_regularizer=l2(0.005)),
    BatchNormalization(),
    Activation("relu"),
    Dropout(0.3),

    
    Dense(1)
])

In [28]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="mse",
    metrics=["mae"]
)

In [29]:
history = model.fit(
    X_train,
    y_train_scaled,         
    validation_data=(X_val, y_val_scaled), 
    epochs=150,
    batch_size=4,
    verbose=1
)

Epoch 1/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.2518 - mae: 0.9702 - val_loss: 6.2706 - val_mae: 2.0655
Epoch 2/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.6892 - mae: 0.7871 - val_loss: 1.6804 - val_mae: 0.8405
Epoch 3/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.7393 - mae: 0.8138 - val_loss: 0.8914 - val_mae: 0.3792
Epoch 4/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5653 - mae: 0.7389 - val_loss: 0.8763 - val_mae: 0.3326
Epoch 5/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4620 - mae: 0.7058 - val_loss: 0.7742 - val_mae: 0.2645
Epoch 6/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3738 - mae: 0.6688 - val_loss: 0.7538 - val_mae: 0.2406
Epoch 7/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3460 - mae: 0.6634 - val_loss: 0.7444 - val_mae: 0.2294
Epoch 8/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2247 - mae: 0.6007 - val_loss: 0.7407 - val_mae: 0.2419
Epoch 9/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2776 - mae: 0.6415 - val_loss: 0.7307 - val_mae: 0.2395
Epoch 10/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2783 - mae: 0.6458 - val_loss: 0.8059 - val_mae: 0.3296
Epoch 11/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1876 - mae: 0.6057 - val_loss: 0.6967 - val_mae: 0.2225
Epoch 12/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2063 - mae: 0.6006 - val_loss: 0.6822 - val_mae: 0.2187
Epoch 13/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1259 - mae: 0.5674 - val_loss: 0.7230 - val_mae: 0.2860
Epoch 14/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0734 - mae: 0.5566 - val_loss: 0.6768 - val_mae: 0.2465
Epoch 15/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1360 - mae: 0.6080 - val_loss: 0.6703 - val_mae: 0.2412
Epoch 16/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0501 - mae: 0.5747 - val_loss: 0.6386 - val_mae: 0.2188
Epoch 17/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9571 - mae: 0.5028 - val_loss: 0.6407 - val_mae: 0.2388
Epoch 18/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0436 - mae: 0.5680 - val_loss: 0.6190 - val_mae: 0.2225
Epoch 19/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9741 - mae: 0.5294 - val_loss: 0.6273 - val_mae: 0.2560
Epoch 20/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9675 - mae: 0.5391 - val_loss: 0.5733 - val_mae: 0.2004
Epoch 21/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9162 - mae: 0.5146 - val_loss: 0.5966 - val_mae: 0.2498
Epoch 22/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9641 - mae: 0.5351 - val_loss: 0.5887 - val_mae: 0.2558
Epoch 23/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8506 - mae: 0.5034 - val_loss: 0.5607 - val_mae: 0.2407
Epoch 24/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9241 - mae: 0.5411 - val_loss: 0.5523 - val_mae: 0.2417
Epoch 25/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8559 - mae: 0.4947 - val_loss: 0.5229 - val_mae: 0.2189
Epoch 26/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8359 - mae: 0.5150 - val_loss: 0.5005 - val_mae: 0.2070
Epoch 27/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8104 - mae: 0.4992 - val_loss: 0.4996 - val_mae: 0.2223
Epoch 28/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9199 - mae: 0.5692 - val_loss: 0.5044 - val_mae: 0.2497
Epoch 29/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8473 - mae: 0.5278 - val_loss: 0.4783 - val_mae: 0.2362
Epoch 30/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.8171 - mae: 0.5281 - val_loss: 0.4489 - val_mae: 0.2088
Epoch 31/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8189 - mae: 0.5376 - val_loss: 0.4277 - val_mae: 0.1951
Epoch 32/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8230 - mae: 0.5538 - val_loss: 0.4365 - val_mae: 0.2271
Epoch 33/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7321 - mae: 0.4833 - val_loss: 0.4170 - val_mae: 0.2171
Epoch 34/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7595 - mae: 0.5244 - val_loss: 0.4089 - val_mae: 0.2201
Epoch 35/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7363 - mae: 0.5179 - val_loss: 0.4001 - val_mae: 0.2266
Epoch 36/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7080 - mae: 0.4968 - val_loss: 0.3685 - val_mae: 0.1989
Epoch 37/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7061 - mae: 0.5042 - val_loss: 0.3782 - val_mae: 0.2223
Epoch 38/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7138 - mae: 0.5281 - val_loss: 0.4260 - val_mae: 0.3128
Epoch 39/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6661 - mae: 0.4964 - val_loss: 0.3941 - val_mae: 0.2899
Epoch 40/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6866 - mae: 0.5107 - val_loss: 0.3260 - val_mae: 0.2003
Epoch 41/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6925 - mae: 0.5347 - val_loss: 0.3062 - val_mae: 0.1867
Epoch 42/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6288 - mae: 0.5032 - val_loss: 0.3279 - val_mae: 0.2368
Epoch 43/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6326 - mae: 0.4950 - val_loss: 0.3575 - val_mae: 0.2873
Epoch 44/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6648 - mae: 0.5407 - val_loss: 0.3692 - val_mae: 0.3072
Epoch 45/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5912 - mae: 0.4990 - val_loss: 0.3194 - val_mae: 0.2576
Epoch 46/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5937 - mae: 0.5008 - val_loss: 0.3419 - val_mae: 0.2960
Epoch 47/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5898 - mae: 0.4956 - val_loss: 0.2609 - val_mae: 0.2060
Epoch 48/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6150 - mae: 0.5317 - val_loss: 0.3456 - val_mae: 0.3446
Epoch 49/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5801 - mae: 0.4992 - val_loss: 0.2728 - val_mae: 0.2603
Epoch 50/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5509 - mae: 0.5007 - val_loss: 0.2236 - val_mae: 0.1895
Epoch 51/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5728 - mae: 0.5210 - val_loss: 0.2346 - val_mae: 0.2138
Epoch 52/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5260 - mae: 0.4770 - val_loss: 0.2006 - val_mae: 0.1692
Epoch 53/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5594 - mae: 0.5179 - val_loss: 0.2326 - val_mae: 0.2295
Epoch 54/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5451 - mae: 0.5000 - val_loss: 0.1866 - val_mae: 0.1682
Epoch 55/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5315 - mae: 0.5171 - val_loss: 0.2031 - val_mae: 0.2067
Epoch 56/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5721 - mae: 0.5505 - val_loss: 0.2560 - val_mae: 0.2781
Epoch 57/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5674 - mae: 0.5322 - val_loss: 0.2166 - val_mae: 0.2378
Epoch 58/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5439 - mae: 0.5220 - val_loss: 0.2534 - val_mae: 0.3024
Epoch 59/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5462 - mae: 0.5326 - val_loss: 0.1676 - val_mae: 0.1764
Epoch 60/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5513 - mae: 0.5281 - val_loss: 0.4945 - val_mae: 0.4958
Epoch 61/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4843 - mae: 0.4899 - val_loss: 0.1732 - val_mae: 0.2018
Epoch 62/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5639 - mae: 0.5422 - val_loss: 0.1728 - val_mae: 0.2113
Epoch 63/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5088 - mae: 0.5113 - val_loss: 0.1578 - val_mae: 0.1841
Epoch 64/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4989 - mae: 0.5023 - val_loss: 0.1864 - val_mae: 0.2350
Epoch 65/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4650 - mae: 0.4853 - val_loss: 0.1637 - val_mae: 0.2091
Epoch 66/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.5180 - mae: 0.5345 - val_loss: 0.1690 - val_mae: 0.2391
Epoch 67/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5147 - mae: 0.5272 - val_loss: 0.2408 - val_mae: 0.3056
Epoch 68/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4592 - mae: 0.4983 - val_loss: 0.1360 - val_mae: 0.1763
Epoch 69/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4533 - mae: 0.4783 - val_loss: 0.2021 - val_mae: 0.2822
Epoch 70/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5077 - mae: 0.5381 - val_loss: 0.1487 - val_mae: 0.2128
Epoch 71/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4424 - mae: 0.4859 - val_loss: 0.1353 - val_mae: 0.1842
Epoch 72/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4676 - mae: 0.4988 - val_loss: 0.1403 - val_mae: 0.1948
Epoch 73/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4468 - mae: 0.4783 - val_loss: 0.1731 - val_mae: 0.2465
Epoch 74/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3973 - mae: 0.4574 - val_loss: 0.1691 - val_mae: 0.2487
Epoch 75/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4765 - mae: 0.5087 - val_loss: 0.1319 - val_mae: 0.1963
Epoch 76/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4875 - mae: 0.5161 - val_loss: 0.1269 - val_mae: 0.1877
Epoch 77/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4670 - mae: 0.5051 - val_loss: 0.1092 - val_mae: 0.1665
Epoch 78/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4608 - mae: 0.4993 - val_loss: 0.1416 - val_mae: 0.2160
Epoch 79/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5150 - mae: 0.5378 - val_loss: 0.3191 - val_mae: 0.4054
Epoch 80/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4388 - mae: 0.4883 - val_loss: 0.1661 - val_mae: 0.2554
Epoch 81/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4462 - mae: 0.4951 - val_loss: 0.1132 - val_mae: 0.1762
Epoch 82/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3870 - mae: 0.4628 - val_loss: 0.2637 - val_mae: 0.3721
Epoch 83/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4709 - mae: 0.5204 - val_loss: 0.1107 - val_mae: 0.1748
Epoch 84/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5068 - mae: 0.5410 - val_loss: 0.1235 - val_mae: 0.1926
Epoch 85/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4882 - mae: 0.5305 - val_loss: 0.1413 - val_mae: 0.2301
Epoch 86/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4117 - mae: 0.4803 - val_loss: 0.1363 - val_mae: 0.2255
Epoch 87/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4362 - mae: 0.5035 - val_loss: 0.1078 - val_mae: 0.1758
Epoch 88/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.4040 - mae: 0.4657 - val_loss: 0.2041 - val_mae: 0.3165
Epoch 89/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4435 - mae: 0.5007 - val_loss: 0.1762 - val_mae: 0.2621
Epoch 90/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4316 - mae: 0.4936 - val_loss: 0.2253 - val_mae: 0.3391
Epoch 91/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4423 - mae: 0.4989 - val_loss: 0.1961 - val_mae: 0.3000
Epoch 92/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4106 - mae: 0.4804 - val_loss: 0.1475 - val_mae: 0.2636
Epoch 93/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4384 - mae: 0.5081 - val_loss: 0.1919 - val_mae: 0.3147
Epoch 94/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4956 - mae: 0.5390 - val_loss: 0.2359 - val_mae: 0.3549
Epoch 95/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4176 - mae: 0.4770 - val_loss: 0.1190 - val_mae: 0.2016
Epoch 96/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4477 - mae: 0.5081 - val_loss: 0.2483 - val_mae: 0.3668
Epoch 97/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4285 - mae: 0.4959 - val_loss: 0.3555 - val_mae: 0.4580
Epoch 98/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4116 - mae: 0.4786 - val_loss: 0.3750 - val_mae: 0.4552
Epoch 99/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4014 - mae: 0.4748 - val_loss: 0.0998 - val_mae: 0.1688
Epoch 100/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3930 - mae: 0.4693 - val_loss: 0.1210 - val_mae: 0.2031
Epoch 101/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4394 - mae: 0.4939 - val_loss: 0.1559 - val_mae: 0.2627
Epoch 102/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4674 - mae: 0.5142 - val_loss: 0.1234 - val_mae: 0.2204
Epoch 103/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4570 - mae: 0.5117 - val_loss: 0.1590 - val_mae: 0.2699
Epoch 104/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4974 - mae: 0.5468 - val_loss: 0.0914 - val_mae: 0.1565
Epoch 105/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3742 - mae: 0.4590 - val_loss: 0.1657 - val_mae: 0.2645
Epoch 106/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4178 - mae: 0.4829 - val_loss: 0.1094 - val_mae: 0.2039
Epoch 107/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4024 - mae: 0.4835 - val_loss: 0.0959 - val_mae: 0.1696
Epoch 108/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.4470 - mae: 0.5091 - val_loss: 0.3138 - val_mae: 0.4390
Epoch 109/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3670 - mae: 0.4608 - val_loss: 0.1475 - val_mae: 0.2689
Epoch 110/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3901 - mae: 0.4796 - val_loss: 0.1326 - val_mae: 0.2355
Epoch 111/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4152 - mae: 0.4844 - val_loss: 0.2059 - val_mae: 0.3219
Epoch 112/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4032 - mae: 0.4752 - val_loss: 0.1115 - val_mae: 0.2062
Epoch 113/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4615 - mae: 0.5128 - val_loss: 0.2291 - val_mae: 0.3225
Epoch 114/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4483 - mae: 0.5000 - val_loss: 0.1623 - val_mae: 0.2727
Epoch 115/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3769 - mae: 0.4664 - val_loss: 0.1509 - val_mae: 0.2656
Epoch 116/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3913 - mae: 0.4636 - val_loss: 0.0965 - val_mae: 0.1834
Epoch 117/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4372 - mae: 0.4842 - val_loss: 0.1013 - val_mae: 0.1936
Epoch 118/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3874 - mae: 0.4708 - val_loss: 0.1074 - val_mae: 0.2079
Epoch 119/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4119 - mae: 0.4879 - val_loss: 0.0833 - val_mae: 0.1627
Epoch 120/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3764 - mae: 0.4621 - val_loss: 0.1125 - val_mae: 0.2074
Epoch 121/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4134 - mae: 0.4802 - val_loss: 0.1487 - val_mae: 0.2613
Epoch 122/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4740 - mae: 0.5280 - val_loss: 0.2239 - val_mae: 0.3603
Epoch 123/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4661 - mae: 0.5158 - val_loss: 0.0848 - val_mae: 0.1629
Epoch 124/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3899 - mae: 0.4801 - val_loss: 0.1631 - val_mae: 0.2690
Epoch 125/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3692 - mae: 0.4529 - val_loss: 0.1648 - val_mae: 0.2518
Epoch 126/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4587 - mae: 0.5348 - val_loss: 0.1041 - val_mae: 0.2040
Epoch 127/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4574 - mae: 0.5107 - val_loss: 0.1171 - val_mae: 0.2018
Epoch 128/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3801 - mae: 0.4764 - val_loss: 0.1051 - val_mae: 0.1932
Epoch 129/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3522 - mae: 0.4605 - val_loss: 0.1228 - val_mae: 0.2255
Epoch 130/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4302 - mae: 0.4980 - val_loss: 0.1401 - val_mae: 0.2376
Epoch 131/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4140 - mae: 0.4980 - val_loss: 0.1030 - val_mae: 0.1945
Epoch 132/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3724 - mae: 0.4652 - val_loss: 0.1201 - val_mae: 0.2169
Epoch 133/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3761 - mae: 0.4707 - val_loss: 0.1309 - val_mae: 0.2480
Epoch 134/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3655 - mae: 0.4596 - val_loss: 0.0824 - val_mae: 0.1775
Epoch 135/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4167 - mae: 0.4924 - val_loss: 0.2959 - val_mae: 0.4227
Epoch 136/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4013 - mae: 0.4895 - val_loss: 0.1308 - val_mae: 0.2447
Epoch 137/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4069 - mae: 0.4993 - val_loss: 0.0973 - val_mae: 0.1824
Epoch 138/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.3556 - mae: 0.4519 - val_loss: 0.2526 - val_mae: 0.3903
Epoch 139/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4277 - mae: 0.4983 - val_loss: 0.1436 - val_mae: 0.2507
Epoch 140/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3893 - mae: 0.4755 - val_loss: 0.1015 - val_mae: 0.2079
Epoch 141/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4098 - mae: 0.4739 - val_loss: 0.2324 - val_mae: 0.3615
Epoch 142/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3711 - mae: 0.4663 - val_loss: 0.1246 - val_mae: 0.2556
Epoch 143/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4087 - mae: 0.4894 - val_loss: 0.2560 - val_mae: 0.4114
Epoch 144/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4625 - mae: 0.5217 - val_loss: 0.6030 - val_mae: 0.6482
Epoch 145/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4200 - mae: 0.4881 - val_loss: 0.1120 - val_mae: 0.2082
Epoch 146/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4231 - mae: 0.4970 - val_loss: 0.1131 - val_mae: 0.2015
Epoch 147/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3955 - mae: 0.4633 - val_loss: 0.0787 - val_mae: 0.1634
Epoch 148/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3747 - mae: 0.4655 - val_loss: 0.1183 - val_mae: 0.2244
Epoch 149/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3644 - mae: 0.4589 - val_loss: 0.1216 - val_mae: 0.2262
Epoch 150/150
88/88 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3983 - mae: 0.4802 - val_loss: 0.1309 - val_mae: 0.2347

In [30]:
pred_scaled = model.predict(X_test).reshape(-1)

pred = y_scaler.inverse_transform(
    pred_scaled.reshape(-1, 1)
).ravel()

print("Actual:", y_test)
print("Predicted:", pred)


mae = mean_absolute_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)




print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)




result = pd.DataFrame({
    "Actual_Price": y_test,
    "Predicted_Price": pred
})

print("\nPredictions:")
display(result)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Actual: [261355 491396 282589 533818 497303 725309 688715 218958 219343 486455
 516979 412726 829955 810986 407430 752395 757071 755515 182831 637139
 557391 824185 383496 374343 804064 422300 595773 271746 277681 606077
 621908 447516 844462 396282 256038 537107 714156 573276 418193 620048
 487657 418703 461714 653008 605175 723621 724002 783302 795626 617269
 478380 390962 569053 773687 801759 603070 457591 606546 725134 552327
 677569 578696 623869 477066 313097 847347 351298 383913 508385 304535
 863356 572882 574087 502512 394484]
Predicted: [325408.34 530200.06 356544.75 576859.25 552885.25 740838.2  744006.1
 337421.75 350238.97 503554.3  570341.6  462738.28 767002.2  760767.6
 457360.66 739049.44 782702.94 730240.06 302536.72 634088.4  595066.8
 782314.1  402849.06 422776.12 766202.9  471293.75 616607.3  353584.6
 352289.1  652753.94 586930.4  434448.53 771925.5  463854.38 349045.7
 591575.   668773.8  589160.44 484737.7  634805.   522732.56 457879.8
 479262.1  623882.06 640541.94 687058.   735699.2  756729.6  814232.1
 609912.2  458960.3  454769.84 580887.8  757653.94 786654.9  598263.94
 488013.12 610217.94 735928.06 586529.94 689283.4  561417.1  628920.3
 514498.03 365005.94 799422.56 409908.16 432966.2  518674.6  391026.38
 770753.1  586919.9  640014.6  549238.06 447235.7 ]
MAE : 41567.078125
RMSE: 50167.58602922808
R2  : 0.9200925230979919

Predictions:

    Actual_Price  Predicted_Price
0         261355     325408.34375
1         491396     530200.06250
2         282589     356544.75000
3         533818     576859.25000
4         497303     552885.25000
..           ...              ...
70        863356     770753.12500
71        572882     586919.87500
72        574087     640014.62500
73        502512     549238.06250
74        394484     447235.68750

[75 rows x 2 columns]